spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  datasource:
    username: admin
    password: 121911
    url: jdbc:postgresql://localhost:32769/nook
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: nook
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

